Resources:
  # Create an EC2 instance
  myInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-south-1a
      ImageId: ami-010aff33ed5991201
      InstanceType: t2.micro
      KeyName: test
      Tags:
      - Key: Name
        Value: Test
